### ISSUE TITLE
Limit

### ISSUE THREAD

**Issue by maverabilisim** [burakaktna/tkgmservice#1]
Merhaba Burak,
Emeğine sağlık. Çok güzel bir uygulama olmuş.
Servis entegrasyonlarını yaptık. Fakat limit hatası alıyoruz. Başınıza geldi mi böyle bir şey?

**Comment by burakaktna** [comment]
> Merhaba Burak,
> 
> Emeğine sağlık. Çok güzel bir uygulama olmuş.
> 
> Servis entegrasyonlarını yaptık. Fakat limit hatası alıyoruz. Başınıza geldi mi böyle bir şey?

Merhaba,

Teşekkür ederim, faydası olduysa ne mutlu bana. Evet, TKGM tarafında böyle bir limit bulunuyor, istekler sunucu tarafında işlendiği için 100 istek sonrası IP limitine takılıyor. Nasıl kullandığınıza bağlı olarak farklı çözüm yolları da mevcuttur; biz istekleri proxy üzerinden göndererek bu sorunu aşmıştık. Her seferinde ya da limit aşıldıkça yeni IP ile istek göndermek sorunu çözecektir. Limitler günlük olarak yenilendiği için kullanılan IP'ler ertesi gün tekrar kullanılabilir.
